version: '2'
services:
    jenkins:
        container_name: jenkins
        build: 
            context: .
        ports: 
            - "3:8080"
        volumes: 
            - ./docker/jenkins/:/var/jenkins_home
            - ./scripts:/var/jenkis_scripts